### ISSUE TITLE
关于Airy雷达的适配

### ISSUE THREAD

**Issue by pcl5** [RuanJY/robosense_fast_lio#4]
您好！我想请教一下，Airy雷达也能采用您修改的这份代码来运行吗？需不需要修改除了Config以外的什么代码呢？比如点云处理逻辑之类的？谢谢啦

**Comment by RuanJY** [comment]
Airy也能，点云处理逻辑 一样
config： scan line=192，已经update，可以试一下
Airy内置imu还没测试

**Comment by alanxuefei** [comment]
> > Airy也能，点云处理逻辑 一样 config： scan line=192，已经update，可以试一下 Airy内置imu还没测试
> 
> 您好，请问使用airy自带的imu建图的时候总是漂移，是不是需要修改相关代码呢?

我在使用 Google Cartographer 时也遇到了同样的问题。

**Comment by alanxuefei** [comment]
> 还没测试过内置imu的性能
> 
> 获取Outlook for Android<https://aka.ms/AAb9ysg>
> […](#)

当Airy放在一个平坦的表面上时，IMU 的读数如下。

这个表现比其他 IMU 更差吗？

```
angular_velocity:
  x: -0.011185277253389359
  y: 0.007456851191818714
  z: 0.0023968450259417295
angular_velocity_covariance:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
linear_acceleration:
  x: -0.0059814453125
  y: -0.0093994140625
  z: -0.996826171875
linear_acceleration_covariance:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
```
